name: Mirror to Work Repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git config
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git config --global init.defaultBranch main

      - name: Mirror to work repository
        env:
          WORK_TOKEN: ${{ secrets.WORK_TOKEN }}
        run: |
          # Clone the target repository
          git clone https://x-access-token:${WORK_TOKEN}@github.com/raghunandhan04work/Hibiz-Ai-Website-Final.git target-repo

          # Copy all files (excluding .git)
          rsync -av --exclude='.git' ./ target-repo/

          # Commit and push changes
          cd target-repo
          git add .

          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to sync"
          else
            git commit -m "Sync from source repository - $(date)"
            git push origin main
          fi
